[build]
target = "wasm32-unknown-unknown"

[unstable]
build-std = ["core", "alloc", "compiler_builtins"]

[target.wasm32-unknown-unknown]
rustflags = [
    "-C",
    "link-arg=-zstack-size=32768",
    "-C",
    "link-arg=--stack-first",

    "-C",
    "link-arg=--initial-memory=65536",
    "-C",
    "link-arg=--max-memory=65536",
]
